In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/bibianglez/first_project/refs/heads/main/data/raw/googleplaystore.csv")
df_review = pd.read_csv('https://raw.githubusercontent.com/bibianglez/first_project/refs/heads/main/data/raw/googleplaystore_user_reviews.csv')

In [17]:
df_review.head()

,App,Translated_Review,Sentiment,Sentiment_Polarity,Sentiment_Subjectivity
0,10 Best Foods for You,I like eat delicious food. That's I'm cooking ...,Positive,1.00,0.533333
1,10 Best Foods for You,This help eating healthy exercise regular basis,Positive,0.25,0.288462
2,10 Best Foods for You,NaN,NaN,NaN,NaN
3,10 Best Foods for You,Works great especially going grocery store,Positive,0.40,0.875000
4,10 Best Foods for You,Best idea us,Positive,1.00,0.300000

In [ ]:
df.shape

In [ ]:
df_review.shape

In [3]:
def clean_column_names(df):
    df.columns = df.columns.str.strip().str.replace(" ", "_").str.replace(".", "_").str.lower()
    return df
clean_column_names(df)

,app,category,rating,reviews,size,installs,type,price,content_rating,genres,last_updated,current_ver,android_ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   app             10841 non-null  object
 1   category        10841 non-null  object
 2   rating          9367 non-null   float64
 3   reviews         10841 non-null  object
 4   size            10841 non-null  object
 5   installs        10841 non-null  object
 6   type            10840 non-null  object
 7   price           10841 non-null  object
 8   content_rating  10840 non-null  object
 9   genres          10841 non-null  object
 10  last_updated    10841 non-null  object
 11  current_ver     10833 non-null  object
 12  android_ver     10838 non-null  object
dtypes: float64(1), object(12)
memory usage: 1.1+ MB

In [5]:
df['rating'] = pd.to_numeric(df['rating'], errors='coerce')

In [6]:
df['reviews'] = pd.to_numeric(df['reviews'], errors='coerce')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   app             10841 non-null  object
 1   category        10841 non-null  object
 2   rating          9367 non-null   float64
 3   reviews         10840 non-null  float64
 4   size            10841 non-null  object
 5   installs        10841 non-null  object
 6   type            10840 non-null  object
 7   price           10841 non-null  object
 8   content_rating  10840 non-null  object
 9   genres          10841 non-null  object
 10  last_updated    10841 non-null  object
 11  current_ver     10833 non-null  object
 12  android_ver     10838 non-null  object
dtypes: float64(2), object(11)
memory usage: 1.1+ MB

In [8]:
df["installs"].unique()

array(['10,000+', '500,000+', '5,000,000+', '50,000,000+', '100,000+',
       '50,000+', '1,000,000+', '10,000,000+', '5,000+', '100,000,000+',
       '1,000,000,000+', '1,000+', '500,000,000+', '50+', '100+', '500+',
       '10+', '1+', '5+', '0+', '0', 'Free'], dtype=object)

In [9]:
df = df.loc[df["installs"] != "Free"]
display(df)

,app,category,rating,reviews,size,installs,type,price,content_rating,genres,last_updated,current_ver,android_ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159.0,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967.0,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510.0,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644.0,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967.0,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,Sya9a Maroc - FR,FAMILY,4.5,38.0,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4.0,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3.0,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114.0,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307.0,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [10]:
df["installs"].unique()

array(['10,000+', '500,000+', '5,000,000+', '50,000,000+', '100,000+',
       '50,000+', '1,000,000+', '10,000,000+', '5,000+', '100,000,000+',
       '1,000,000,000+', '1,000+', '500,000,000+', '50+', '100+', '500+',
       '10+', '1+', '5+', '0+', '0'], dtype=object)

In [11]:
df['installs'] = df['installs'].str.replace('+', '', regex=False).str.replace(',', '', regex=False)
df['installs'] = df['installs'].astype(int)
df["installs"].unique()

C:\Users\fotos\AppData\Local\Temp\ipykernel_11824\2351854670.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['installs'] = df['installs'].str.replace('+', '', regex=False).str.replace(',', '', regex=False)
C:\Users\fotos\AppData\Local\Temp\ipykernel_11824\2351854670.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['installs'] = df['installs'].astype(int)

array([     10000,     500000,    5000000,   50000000,     100000,
            50000,    1000000,   10000000,       5000,  100000000,
       1000000000,       1000,  500000000,         50,        100,
              500,         10,          1,          5,          0])

In [12]:
#checking for duplicates
display(df['app'].value_counts())

app
ROBLOX                                                9
CBS Sports App - Scores, News, Stats & Watch Live     8
ESPN                                                  7
Duolingo: Learn Languages Free                        7
Candy Crush Saga                                      7
                                                     ..
Meet U - Get Friends for Snapchat, Kik & Instagram    1
U-Report                                              1
U of I Community Credit Union                         1
Waiting For U Launcher Theme                          1
iHoroscope - 2018 Daily Horoscope & Astrology         1
Name: count, Length: 9659, dtype: int64

In [13]:
display(df[df.duplicated(subset=['app'] , keep=False)].sort_values(by='app'))

,app,category,rating,reviews,size,installs,type,price,content_rating,genres,last_updated,current_ver,android_ver
1393,10 Best Foods for You,HEALTH_AND_FITNESS,4.0,2490.0,3.8M,500000,Free,0,Everyone 10+,Health & Fitness,"February 17, 2017",1.9,2.3.3 and up
1407,10 Best Foods for You,HEALTH_AND_FITNESS,4.0,2490.0,3.8M,500000,Free,0,Everyone 10+,Health & Fitness,"February 17, 2017",1.9,2.3.3 and up
2543,1800 Contacts - Lens Store,MEDICAL,4.7,23160.0,26M,1000000,Free,0,Everyone,Medical,"July 27, 2018",7.4.1,5.0 and up
2322,1800 Contacts - Lens Store,MEDICAL,4.7,23160.0,26M,1000000,Free,0,Everyone,Medical,"July 27, 2018",7.4.1,5.0 and up
2385,2017 EMRA Antibiotic Guide,MEDICAL,4.4,12.0,3.8M,1000,Paid,$16.99,Everyone,Medical,"January 27, 2017",1.0.5,4.0.3 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3202,trivago: Hotels & Travel,TRAVEL_AND_LOCAL,4.2,219848.0,Varies with device,50000000,Free,0,Everyone,Travel & Local,"August 2, 2018",Varies with device,Varies with device
3118,trivago: Hotels & Travel,TRAVEL_AND_LOCAL,4.2,219848.0,Varies with device,50000000,Free,0,Everyone,Travel & Local,"August 2, 2018",Varies with device,Varies with device
3103,trivago: Hotels & Travel,TRAVEL_AND_LOCAL,4.2,219848.0,Varies with device,50000000,Free,0,Everyone,Travel & Local,"August 2, 2018",Varies with device,Varies with device
8291,wetter.com - Weather and Radar,WEATHER,4.2,189310.0,38M,10000000,Free,0,Everyone,Weather,"August 6, 2018",Varies with device,Varies with device
3652,wetter.com - Weather and Radar,WEATHER,4.2,189313.0,38M,10000000,Free,0,Everyone,Weather,"August 6, 2018",Varies with device,Varies with device

In [14]:
df.drop_duplicates(subset=['app'], keep='first', inplace=True)
display(df['app'].value_counts())

C:\Users\fotos\AppData\Local\Temp\ipykernel_11824\3372002112.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop_duplicates(subset=['app'], keep='first', inplace=True)

app
Photo Editor & Candy Camera & Grid & ScrapBook    1
Tic Tac CK                                        1
INFAMY RO                                         1
CK Call NEW                                       1
Ck Coif                                           1
                                                 ..
Bike Race Free - Top Motorcycle Racing Games      1
Dance School Stories - Dance Dreams Come True     1
3D Bowling                                        1
Mind Games Pro                                    1
iHoroscope - 2018 Daily Horoscope & Astrology     1
Name: count, Length: 9659, dtype: int64

In [16]:
df_merge = pd.merge(df, df_review, on= 'app', how='inner')
df_merge.shape

KeyError: 'app'

In [18]:
# top 25 installed apps
top_25_installs = df.nlargest(25, 'installs')
display(top_25_installs[['app', 'installs','genres']].sort_values(by='genres'))

,app,installs,genres
1654,Subway Surfers,1000000000,Arcade
152,Google Play Books,1000000000,Books & Reference
371,Google Duo - High Quality Video Calls,500000000,Communication
347,imo free video calls and chat,500000000,Communication
342,Viber Messenger,500000000,Communication
378,UC Browser - Fast Download Private & Secure,500000000,Communication
403,LINE: Free Calls & Messages,500000000,Communication
341,Hangouts,1000000000,Communication
335,Messenger – Text and Video Chat for Free,1000000000,Communication
336,WhatsApp Messenger,1000000000,Communication
338,Google Chrome: Fast & Secure,1000000000,Communication
340,Gmail,1000000000,Communication
391,Skype - free IM & video calls,1000000000,Communication
865,Google Play Games,1000000000,Entertainment
3736,Google News,1000000000,News & Magazines
2808,Google Photos,1000000000,Photography
3454,Google Drive,1000000000,Productivity
2554,Google+,1000000000,Social
2545,Instagram,1000000000,Social
2544,Facebook,1000000000,Social
3234,Google,1000000000,Tools
3117,Maps - Navigate & Explore,1000000000,Travel & Local
3127,Google Street View,1000000000,Travel & Local
3665,YouTube,1000000000,Video Players & Editors
3687,Google Play Movies & TV,1000000000,Video Players & Editors

In [19]:
# top25 best rated apps
top_25_rating = df.nlargest(25, 'rating')
display(top_25_rating[['app', 'rating','genres']].sort_values(by='genres'))

,app,rating,genres
329,Hojiboy Tojiboyev Life Hacks,5.0,Comics
612,American Girls Mobile Numbers,5.0,Dating
615,Awake Dating,5.0,Dating
633,Spine- The dating app,5.0,Dating
636,Girls Live Talk - Free Text and Video Chat,5.0,Dating
640,Online Girls Chat Group,5.0,Dating
654,Speeding Joyride & Car Meet App,5.0,Dating
1038,Mindvalley U Tallinn 2018,5.0,Events
1030,Prosperity,5.0,Events
1028,SUMMER SONIC app,5.0,Events
1547,Eternal life,5.0,Libraries & Demo
2459,Anatomy & Physiology Vocabulary Exam Review App,5.0,Medical
2458,You're an Anime,5.0,Medical
2457,PrimeDelivery,5.0,Medical
2455,FoothillsVet,5.0,Medical
2454,KBA-EZ Health Guide,5.0,Medical
2452,Galaxies of Hope,5.0,Medical
2271,FHR 5-Tier 2.0,5.0,Medical
2448,Dermatology Atlas (Colored & Illustrative),5.0,Medical
2445,Labs on Demand,5.0,Medical
2427,Sway Medical,5.0,Medical
2472,NCLEX Multi-topic Nursing Exam Review-Quiz & n...,5.0,Medical
2262,Super Hearing Secret Voices Recorder PRO,5.0,Medical
2450,Tablet Reminder,5.0,Medical
2477,Basics of Orthopaedics,5.0,Medical

In [20]:
# top5 morst downloaded genre
top_5_genre = df['genres'].value_counts().head(5)
display(top_5_genre)

genres
Tools            826
Entertainment    561
Education        510
Business         420
Medical          395
Name: count, dtype: int64

In [21]:
df_tools = df[df['genres'] == 'Tools']
top_10_tools = df_tools.nlargest(10, 'installs')
display(top_10_tools[['app', 'installs', 'genres']])

                                                    app    installs genres
3234                                             Google  1000000000  Tools
3235                                   Google Translate   500000000  Tools
3255                         SHAREit - Transfer & Share   500000000  Tools
3265                       Gboard - the Google Keyboard   500000000  Tools
4005            Clean Master- Space Cleaner & Antivirus   500000000  Tools
7536  Security Master - Antivirus, VPN, AppLock, Boo...   500000000  Tools
3239  Cache Cleaner-DU Speed Booster (booster & clea...   100000000  Tools
3243                                        Device Help   100000000  Tools
3244                                    Account Manager   100000000  Tools
3261                                 Samsung Calculator   100000000  Tools

In [22]:
#does people pay for apps?
paid_apps = df['type'].value_counts()
display(paid_apps)

type
Free    8902
Paid     756
Name: count, dtype: int64

In [26]:
paid_vs_free = df.groupby('type').agg(apps_nr=('type', 'count'),total_downloads=('installs', 'sum'))
total_downloads = df['installs'].sum()
paid_vs_free['downloads_perc'] = (paid_vs_free['total_downloads'] / total_downloads) * 100
display(paid_vs_free.style.set_caption("paid vs free apps"))

In [27]:
paid_vs_free = df.groupby('type').agg(apps_nr=('type', 'count'),total_downloads=('installs', 'sum'))

total_downloads = df['installs'].sum()
total_apps = paid_vs_free['apps_nr'].sum()  

paid_vs_free['apps_perc'] = (paid_vs_free['apps_nr'] / total_apps) * 100
paid_vs_free['downloads_perc'] = (paid_vs_free['total_downloads'] / total_downloads) * 100

display(paid_vs_free.style.set_caption("paid vs free apps").format({'total_downloads': '{:,.0f}','apps_perc': '{:.2f}%','downloads_perc': '{:.2f}%'}))

In [23]:
#which app was the one that provided more revenew
df['price'] = df['price'].astype(str).str.replace('$', '', regex=False)
df['price'] = pd.to_numeric(df['price'], errors='coerce').fillna(0.0)

C:\Users\fotos\AppData\Local\Temp\ipykernel_11824\312363402.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['price'] = df['price'].astype(str).str.replace('$', '', regex=False)
C:\Users\fotos\AppData\Local\Temp\ipykernel_11824\312363402.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['price'] = pd.to_numeric(df['price'], errors='coerce').fillna(0.0)

In [24]:
df['gain'] = df['installs'] * df['price']
df_paid = df[(df['type'] == 'Paid') & (df['gain'] > 0)]
top_10_income = df_paid.nlargest(10, 'gain')
display(top_10_income[['app', 'installs', 'price', 'gain']])

C:\Users\fotos\AppData\Local\Temp\ipykernel_11824\899296073.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['gain'] = df['installs'] * df['price']

                                app  installs   price        gain
2241                      Minecraft  10000000    6.99  69900000.0
5351                      I am rich    100000  399.99  39999000.0
5356              I Am Rich Premium     50000  399.99  19999500.0
4034                  Hitman Sniper  10000000    0.99   9900000.0
7417  Grand Theft Auto: San Andreas   1000000    6.99   6990000.0
2883            Facetune - For Free   1000000    5.99   5990000.0
5578        Sleep as Android Unlock   1000000    5.99   5990000.0
8804            DraStic DS Emulator   1000000    4.99   4990000.0
4367       I'm Rich - Trump Edition     10000  400.00   4000000.0
4362                     💎 I'm rich     10000  399.99   3999900.0

In [28]:
df['gain'] = df['installs'] * df['price']

df_paid = df[(df['type'] == 'Paid')& (df['gain'] > 0)& (~df['app'].str.contains('rich', case=False, na=False))]
top_10_income = df_paid.nlargest(10, 'gain')
display(top_10_income[['app', 'installs', 'price', 'gain']])

C:\Users\fotos\AppData\Local\Temp\ipykernel_11824\1336215760.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['gain'] = df['installs'] * df['price']

                                app  installs  price        gain
2241                      Minecraft  10000000   6.99  69900000.0
4034                  Hitman Sniper  10000000   0.99   9900000.0
7417  Grand Theft Auto: San Andreas   1000000   6.99   6990000.0
2883            Facetune - For Free   1000000   5.99   5990000.0
5578        Sleep as Android Unlock   1000000   5.99   5990000.0
8804            DraStic DS Emulator   1000000   4.99   4990000.0
4133                   Weather Live    500000   5.99   2995000.0
2242     Card Wars - Adventure Time   1000000   2.99   2990000.0
5631        Five Nights at Freddy's   1000000   2.99   2990000.0
7355                        Threema   1000000   2.99   2990000.0

In [25]:
#hor many categories there are and how popular are each
categories_top = df['category'].value_counts()
display(categories_top)

category
FAMILY                 1832
GAME                    959
TOOLS                   827
BUSINESS                420
MEDICAL                 395
PERSONALIZATION         376
PRODUCTIVITY            374
LIFESTYLE               369
FINANCE                 345
SPORTS                  325
COMMUNICATION           315
HEALTH_AND_FITNESS      288
PHOTOGRAPHY             281
NEWS_AND_MAGAZINES      254
SOCIAL                  239
BOOKS_AND_REFERENCE     222
TRAVEL_AND_LOCAL        219
SHOPPING                202
DATING                  171
VIDEO_PLAYERS           163
MAPS_AND_NAVIGATION     131
EDUCATION               119
FOOD_AND_DRINK          112
ENTERTAINMENT           102
AUTO_AND_VEHICLES        85
LIBRARIES_AND_DEMO       84
WEATHER                  79
HOUSE_AND_HOME           74
EVENTS                   64
ART_AND_DESIGN           64
PARENTING                60
COMICS                   56
BEAUTY                   53
Name: count, dtype: int64

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
sns.set_theme(style="whitegrid")

cat_counts = df['category'].value_counts().reset_index()
cat_counts.columns = ['Categoría', 'Cantidad_Apps']

fig, ax = plt.subplots(figsize=(11, 10))

sns.barplot(
    x='Cantidad_Apps', 
    y='Categoría', 
    data=cat_counts, 
    palette='viridis',
    ax=ax
)

for i, v in enumerate(cat_counts['Cantidad_Apps']):
    ax.text(v + 12, i, str(v), color='black', fontsize=9, va='center')

ax.set_title('Apps by category', fontsize=14, weight='bold', pad=15)
ax.set_xlabel('Apps', fontsize=12)
ax.set_ylabel('categories', fontsize=12)

plt.tight_layout()

plt.show()

In [ ]:
df_reviews = pd.read_csv("https://raw.githubusercontent.com/bibianglez/first_project/refs/heads/main/data/raw/googleplaystore_user_reviews.csv")
df_reviews.columns = df_reviews.columns.str.strip().str.lower() 

df_merged = pd.merge(df, df_reviews, on='app', how='inner')

In [ ]:
df_merged.shape

In [ ]:



sns.set_theme(style="whitegrid")
plt.figure(figsize=(12, 6))

top_categories = df.groupby('category')['installs'].sum().sort_values(ascending=False).head(10).reset_index()

ax = sns.barplot(x='installs', y='category', data=top_categories, palette='viridis')

ax.xaxis.set_major_formatter(plt.FuncFormatter(lambda x, loc: "{:,}".format(int(x))))

plt.title('top 10 categories of downloaded apps', fontsize=14, pad=15)
plt.xlabel('Global installation', fontsize=12)
plt.ylabel('Category', fontsize=12)
plt.tight_layout()
plt.show()

In [ ]:

df_health_social = df_merged[df_merged['category'].isin(['HEALTH_AND_FITNESS', 'MEDICAL', 'COMMUNICATION'])]
df_health_social = df_health_social.dropna(subset=['sentiment_polarity'])

categories_of_interest = ['HEALTH_AND_FITNESS', 'MEDICAL', 'COMMUNICATION']
df_filtrado = df_merged[df_merged['category'].isin(categories_of_interest)].dropna(subset=['sentiment_polarity'])

plt.figure(figsize=(11, 6))

for cat in categories_of_interest:
    subset = df_filtrado[df_filtrado['category'] == cat]
    sns.kdeplot(data=subset['sentiment_polarity'], label=cat, fill=True, alpha=0.2, linewidth=2)

plt.axvline(0, color='gray', linestyle='--', alpha=0.7, label='Neutral')
plt.title('sentiment by category', fontsize=14, pad=15)
plt.xlabel('sentiment polarity (from -1 to 1)', fontsize=12)
plt.ylabel('density of opinions', fontsize=12)
plt.xlim(-1, 1) 
plt.legend(title='categories')
plt.tight_layout()
plt.show()

In [ ]:
social_interest = ['HEALTH_AND_FITNESS', 'MEDICAL', 'EDUCATION', 'FINANCE', 'COMMUNICATION']
df_social_categories = df[df['category'].isin(social_interest)]

plt.figure(figsize=(10, 6))

ax = sns.countplot(x='category', hue='type', data=df_social_categories, palette='muted')

plt.title('free vs paid apps in the social environment', fontsize=14, pad=15)
plt.xlabel('category', fontsize=12)
plt.ylabel('number of apps', fontsize=12)
plt.xticks(rotation=15)
plt.legend(title='kind of app')
plt.tight_layout()

In [ ]:
fig, axes = plt.subplots(1, 2, figsize=(18, 5.5))
fig.suptitle('Analysis between paid vs free apps', fontsize=16, weight='bold', y=1.05)

df_clean_rating = df.dropna(subset=['rating'])

sns.kdeplot(
    data=df_clean_rating[df_clean_rating['type'] == 'Paid'], 
    x='rating', fill=True, color='crimson', ax=axes[0], linewidth=2
)
axes[0].set_title('Paid apps distribution', fontsize=12)
axes[0].set_xlabel('Rating', fontsize=10)
axes[0].set_ylabel('apps density', fontsize=10)
axes[0].set_xlim(3.0, 5.0)  

#-----------------------------------------------------------------

sns.kdeplot(
    data=df_clean_rating[df_clean_rating['type'] == 'Free'], 
    x='rating', fill=True, color='teal', ax=axes[1], linewidth=2
)
axes[1].set_title('Free apps distributin', fontsize=12)
axes[1].set_xlabel('Rating', fontsize=10)
axes[1].set_ylabel('') 
axes[1].set_xlim(3.0, 5.0) 

# ------------------------------------------------------------



plt.tight_layout()
plt.show()

In [ ]:
bins = [0, 3.5, 4.0, 4.5, 5.0]
labels = ['< 3.5', '3.5 - 4.0', '4.0 - 4.5', '4.5 - 5.0']
df_clean_rating['rating_range'] = pd.cut(df_clean_rating['rating'], bins=bins, labels=labels)
heatmap_data = pd.crosstab(df_clean_rating['rating_range'], df_clean_rating['type'], normalize='columns') * 100

sns.heatmap(
    heatmap_data, annot=True, fmt=".1f", cmap="YlGnBu", 
    cbar_kws={'label': '% same type apps'}, annot_kws={"size": 11}
)
axes[0].set_title('ratings concentration', fontsize=12)
axes[0].set_xlabel('apps type', fontsize=10)
axes[0].set_ylabel('Rating', fontsize=10)
axes[0].invert_yaxis()
plt.tight_layout()
plt.show()

In [ ]:
# now I?m going to try to find apps that are aiming for male and/or female public by using stereotipical words. 25 words each

keywords_women = ['period', 'ovulation', 'pregnancy', 'makeup', 'nails', 'female', 'girl', 'women', 'hair', 'blw', 'baby', 'hairstyle', 'beauty', 'Dresses', 'maternity', "nursing", "breastfeeding",'pilates', 'yoga', 'weight', 'diet', 'wrinkle', 'fashion', 'wedding']
keywords_men = ['beard', 'shaving', 'barber', 'testosterone', 'male', 'boy', 'men\'s', 'Football', 'soccer', 'sport', 'sports', 'golf', 'invest', 'investment','body builder', 'bodybuilding', 'muscle', 'boxing', 'NBA', 'gun', 'cars', 'truck', 'f1', 'race', 'racing']

women_pattern = '|'.join(keywords_women) 
men_pattern = '|'.join(keywords_men)

df_women = df[df['app'].str.contains(women_pattern, case=False, na=False)]
df_men = df[df['app'].str.contains(men_pattern, case=False, na=False)]

print(f"apps in the women's pattern:{len(df_women)}")
print(f"apps in the men's pattern:{len(df_men)}")

In [ ]:
df_gender = df.drop_duplicates(subset=['app']).copy()

keywords_women = ['period', 'ovulation', 'pregnancy', 'makeup', 'nails', 'female', 'girl', 'women', 'hair', 'blw', 'baby', 'hairstyle', 'beauty', 'Dresses', 'maternity', "nursing", "breastfeeding",'pilates', 'yoga', 'weight', 'diet', 'wrinkle', 'fashion', 'wedding']
keywords_men = ['beard', 'shaving', 'barber', 'testosterone', 'male', 'boy', 'men\'s', 'Football', 'soccer', 'sport', 'sports', 'golf', 'invest', 'investment','body builder', 'bodybuilding', 'muscle', 'boxing', 'NBA', 'gun', 'cars', 'truck', 'f1', 'race', 'racing']

pattern_women = '|'.join(keywords_women)
pattern_men = '|'.join(keywords_men)

women_focused = df_gender['app'].str.contains(pattern_women, case=False, na=False)
men_focused = df_gender['app'].str.contains(pattern_men, case=False, na=False)

df_gender['target_gender'] = 'General'

df_gender.loc[women_focused, 'target_gender'] = 'Women-focused'
df_gender.loc[men_focused, 'target_gender'] = 'Men-focused'


df_segmented = df_gender[df_gender['target_gender'] != 'General'].copy()

columns_to_show = ['app', 'category', 'rating', 'installs', 'target_gender']
display(df_segmented[columns_to_show].head(10))

In [ ]:
fig, axes = plt.subplots(1, 2, figsize=(15, 6))
fig.suptitle('Comparison between genres', fontsize=16, weight='bold', y=1.02)
sns.set_theme(style="whitegrid")


order_gender = ['Women-focused', 'Men-focused']
sns.countplot(
    data=df_segmented, 
    x='target_gender', 
    palette=['#ff7fa7', '#4b9cd3'], 
    order=order_gender,
    ax=axes[0]
)
axes[0].set_title('total apps in google play', fontsize=12, pad=10)
axes[0].set_xlabel('genre-focused', fontsize=11)
axes[0].set_ylabel('number of apps', fontsize=11)

for p in axes[0].patches:
    axes[0].annotate(f'{int(p.get_height())}', (p.get_x() + p.get_width() / 2., p.get_height()),
                ha='center', va='center', xytext=(0, 5), textcoords='offset points', fontsize=10, weight='bold')


sns.barplot(
    data=df_segmented, 
    x='target_gender', 
    y='installs', 
    palette=['#ff7fa7', '#4b9cd3'], 
    order=order_gender,
    errorbar=None,
    ax=axes[1]
)
axes[1].set_title('downloads mean by app', fontsize=12, pad=10)
axes[1].set_xlabel('genre-focused', fontsize=11)
axes[1].set_ylabel('mean of installations', fontsize=11)

axes[1].yaxis.set_major_formatter(plt.FuncFormatter(lambda x, loc: "{:,}".format(int(x))))

for p in axes[1].patches:
    axes[1].annotate(f'{int(p.get_height()):,}', (p.get_x() + p.get_width() / 2., p.get_height()),
                ha='center', va='center', xytext=(0, 5), textcoords='offset points', fontsize=10, weight='bold')

plt.tight_layout()
plt.show()

In [ ]:
#df_beauty = df[df['category'] == 'BEAUTY']
#display(df_beauty[['app', 'rating', 'installs']].sort_values(by='installs', ascending=False))

In [ ]:
#df_finance = df[df['category'] == 'FINANCE']
#display(df_finance[['app', 'rating', 'installs']].head(50).sort_values(by='installs', ascending=False))

In [ ]:
#df_sport = df[df['category'] == 'SPORTS']
#display(df_sport[['app', 'rating', 'installs']].head(50).sort_values(by='installs', ascending=False))

In [ ]:
#df_lifestyle = df[df['category'] == 'LIFESTYLE']
#display(df_lifestyle[['app', 'rating', 'installs']].head(50).sort_values(by='installs', ascending=False))

In [ ]:
#df_cars = df[df['category'] == 'AUTO_AND_VEHICLES']
#display(df_cars[['app', 'rating', 'installs']].head(50).sort_values(by='installs', ascending=False))

# Supply

In [ ]:
plt.figure(figsize=(8, 5))
sns.set_theme(style="whitegrid")

order_gender = ['Women-focused', 'Men-focused']
colors = ['#ff7fa7', '#4b9cd3']

ax = sns.countplot(
    data=df_segmented, 
    x='target_gender', 
    palette=colors, 
    order=order_gender,
    width=0.4
)

for p in ax.patches:
    ax.annotate(f'{int(p.get_height())}', (p.get_x() + p.get_width() / 2., p.get_height()),
                ha='center', va='center', xytext=(0, 5), textcoords='offset points', fontsize=11, weight='bold')

plt.title('Total Apps in Google Play by Genre Focus', fontsize=13, weight='bold', pad=15)
plt.xlabel('Genre-focused', fontsize=11)
plt.ylabel('Number of Apps', fontsize=11)
plt.tight_layout()
plt.show()

In [ ]:
plt.figure(figsize=(8, 6))
sns.set_theme(style="whitegrid")

order_gender = ['Women-focused', 'Men-focused']
colors = ['#ff7fa7', '#4b9cd3']

ax = sns.barplot(
    data=df_segmented, 
    x='target_gender', 
    y='installs', 
    palette=colors, 
    order=order_gender,
    errorbar=None,
    width=0.4
)

ax.yaxis.set_major_formatter(plt.FuncFormatter(lambda x, loc: "{:,}".format(int(x))))

for p in ax.patches:
    if p.get_height() > 0:
        ax.annotate(
            f'{int(p.get_height()):,}', 
            (p.get_x() + p.get_width() / 2., p.get_height()),
            ha='center', va='bottom', 
            xytext=(0, 8),             
            textcoords='offset points', 
            fontsize=10, weight='bold',               
        )

ax.set_ylim(0, df_segmented.groupby('target_gender')['installs'].mean().max() * 1.25)

plt.title('Downloads Mean by App and Genre Focus', fontsize=13, weight='bold', pad=15)
plt.xlabel('Genre-focused', fontsize=11)
plt.ylabel('Mean of Installations', fontsize=11)
plt.tight_layout()
plt.show()

In [ ]:
plt.figure(figsize=(8, 6))
sns.set_theme(style="whitegrid")

ax = sns.barplot(
    data=df_segmented, 
    x='target_gender', 
    y='reviews', 
    palette=colors, 
    order=order_gender,
    errorbar=None,
    width=0.4
)

ax.yaxis.set_major_formatter(plt.FuncFormatter(lambda x, loc: "{:,}".format(int(x))))

for p in ax.patches:
    if p.get_height() > 0:
        ax.annotate(
            f'{int(p.get_height()):,}', 
            (p.get_x() + p.get_width() / 2., p.get_height()),
            ha='center', va='bottom', 
            xytext=(0, 8),             
            textcoords='offset points', 
            fontsize=10, weight='bold',
            rotation=30                
        )

ax.set_ylim(0, df_segmented.groupby('target_gender')['reviews'].mean().max() * 1.25)

plt.title('Reviews Mean by App and Genre Focus', fontsize=13, weight='bold', pad=15)
plt.xlabel('Genre-focused', fontsize=11)
plt.ylabel('Mean of Reviews', fontsize=11)
plt.tight_layout()
plt.show()

In [ ]:
df_plot = df_segmented.dropna(subset=['rating', 'reviews']).copy()


plt.figure(figsize=(10, 7))

sns.set_theme(style="darkgrid")

colors = {'Women-focused': '#ff007f', 'Men-focused': '#00bfff'}

ax = sns.scatterplot(
    data=df_plot,
    x='rating',
    y='reviews',
    hue='target_gender',
    palette=colors,
    size='reviews',       
    sizes=(50, 500),              
    alpha=0.75,                    
    edgecolor='#2c3e50',            
    linewidth=0.6,
    style='target_gender',                      
)


ax.set_yscale('log')

ax.yaxis.set_major_formatter(plt.FuncFormatter(lambda x, loc: "{:,}".format(int(x))))
ax.set_xlim(2.5, 5.1)

plt.title('App Landscape: Rating, Reviews and Genre Focus Density', fontsize=14, weight='bold', pad=20)
plt.xlabel('App Rating', fontsize=12, weight='bold')
plt.ylabel('Number of Reviews (Scale Log)', fontsize=12, weight='bold')

line1 = plt.Line2D([0], [0], marker='o', color='white', markerfacecolor='#ff7fa7', markersize=12, label='Women-focused')
line2 = plt.Line2D([0], [0], marker='o', color='white', markerfacecolor='#4b9cd3', markersize=12, label='Men-focused')
plt.legend(handles=[line1, line2], title='Genre Focus', title_fontsize='11', loc='upper left', frameon=True)

plt.tight_layout()
plt.show()

In [ ]:
mis_colores = ['#ff007f', '#00bfff', '#e41a1c', '#377eb8', '#984ea3']
nombres = ['Women-focused (#ff007f)', 'Men-focused (#00bfff)']

# Dibujar la paleta en pantalla
sns.palplot(mis_colores)
for i, nombre in enumerate(nombres):
    plt.text(i, 0.6, nombre, ha='center', va='center', fontsize=11, weight='bold')
plt.title('Tus Nuevos Colores Eléctricos para el Proyecto', fontsize=13, pad=10)
plt.show()

In [ ]:
# 1. Cargamos los colores de la paleta "dark" por defecto (suele traer 6 o 10 colores)
paleta_dark = sns.color_palette("viridis")

# 2. Dibujamos la tira de colores en el cuaderno
sns.palplot(paleta_dark)

# Opcional: Le ponemos un título bonito
plt.title('Muestra de la Paleta "dark" de Seaborn', fontsize=12, pad=10)
plt.show()

In [ ]:
df_merge = pd.merge(df, df_review, on= 'app', how='inner')
df_merge.shape